# Copyright 2017-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
#
#   Time-stamp: <2022-01-30 22:14:47 IST>
#   Touched: Thu Feb 18 17:27:57 2021 +0530 <enometh@net.meer>
#   Bugs-To: enometh@net.meer
#   Status: Experimental.  Do not redistribute
#   Copyright (C) 2021 Madhu.  All Rights Reserved.
#
# ;madhu 210218 0.2.15 - Auto-Generated by cargo-ebuild 0.3.1
#    WARNING: fuchsia-cprng uses a license-file, not handled
#    WARNING: ring uses a license-file, not handled
# files/ from https://data.gpo.zugaina.org/gentoo/dev-util/sccache/files/
#
# ;madhu 220130 0.2.16_alpha_p1  "0.2.16-alpha.0"  5b751f473
# cargo-ebuild produces 283 deps only 200 are used in the build, which
# are retained here.

EAPI=7

MY_COMMIT=5b751f473e098d68b8965300148ed6538a40a1d9

CRATES="
	libc-0.2.107
	autocfg-1.0.1
	proc-macro2-1.0.32
	cfg-if-1.0.0
	unicode-xid-0.2.2
	syn-1.0.81
	log-0.4.14
	memchr-2.4.1
	pin-project-lite-0.2.7
	futures-core-0.3.17
	version_check-0.9.3
	futures-sink-0.3.17
	once_cell-1.8.0
	proc-macro-hack-0.5.19
	typenum-1.14.0
	bytes-1.1.0
	itoa-0.4.8
	proc-macro-nested-0.1.7
	futures-task-0.3.17
	pkg-config-0.3.22
	futures-channel-0.3.17
	slab-0.4.5
	futures-io-0.3.17
	pin-utils-0.1.0
	serde_derive-1.0.130
	fnv-1.0.7
	unicode-width-0.1.9
	serde-1.0.130
	openssl-0.10.38
	ppv-lite86-0.2.15
	foreign-types-shared-0.1.1
	getrandom-0.1.16
	lazy_static-1.4.0
	bitflags-1.3.2
	remove_dir_all-0.5.3
	native-tls-0.2.8
	tinyvec_macros-0.1.0
	byteorder-1.4.3
	matches-0.1.9
	hashbrown-0.11.2
	httparse-1.5.1
	percent-encoding-2.1.0
	ryu-1.0.5
	openssl-probe-0.1.4
	try-lock-0.2.3
	crc32fast-1.2.1
	subtle-2.4.1
	unicode-bidi-0.3.7
	tower-service-0.3.1
	encoding_rs-0.8.29
	httpdate-1.0.1
	arrayvec-0.5.2
	serde_json-1.0.69
	cfg-if-0.1.10
	zstd-safe-3.0.1+zstd.1.4.9
	opaque-debug-0.3.0
	async-trait-0.1.51
	anyhow-1.0.45
	utf8parse-0.2.0
	bytes-0.5.6
	regex-syntax-0.6.25
	pin-project-lite-0.1.12
	md5-0.3.8
	adler-1.0.2
	semver-parser-0.7.0
	mime-0.3.16
	cpufeatures-0.2.1
	boxfnonce-0.1.1
	bufstream-0.1.4
	percent-encoding-1.0.1
	either-1.6.1
	constant_time_eq-0.1.5
	base64-0.13.0
	humantime-2.1.0
	dtoa-0.4.8
	same-file-1.0.6
	ipnet-2.3.1
	strsim-0.8.0
	arrayref-0.3.6
	termcolor-1.1.2
	untrusted-0.7.1
	vec_map-0.8.2
	tower-layer-0.3.1
	ansi_term-0.11.0
	spin-0.5.2
	language-tags-0.2.2
	number_prefix-0.4.0
	linked-hash-map-0.5.4
	ar-0.8.0
	counted-array-0.1.2
	futures-macro-0.3.17
	futures-util-0.3.17
	tokio-1.13.0
	indexmap-1.7.0
	num-traits-0.2.14
	num-integer-0.1.44
	miniz_oxide-0.4.4
	generic-array-0.14.4
	unicase-2.6.0
	getopts-0.2.21
	textwrap-0.11.0
	http-0.2.5
	foreign-types-0.3.2
	tinyvec-1.5.1
	tracing-core-0.1.21
	form_urlencoded-1.0.1
	base64-0.10.1
	semver-0.9.0
	tokio-0.2.25
	walkdir-2.3.2
	pulldown-cmark-0.0.3
	unicode-normalization-0.1.19
	want-0.3.0
	conhash-0.4.0
	aho-corasick-0.7.18
	jobserver-0.1.24
	num_cpus-1.13.0
	signal-hook-registry-1.4.0
	mio-0.7.14
	rand-0.4.6
	getrandom-0.2.3
	socket2-0.4.2
	iovec-0.1.4
	time-0.1.43
	atty-0.2.14
	xattr-0.2.2
	filetime-0.2.15
	dirs-sys-0.3.6
	unix_socket-0.5.0
	daemonize-0.4.1
	which-4.2.2
	quote-1.0.10
	http-body-0.4.4
	cc-1.0.72
	idna-0.2.3
	rand_core-0.5.1
	regex-1.5.4
	rand_core-0.6.3
	uuid-0.8.2
	bytes-0.4.12
	clap-2.33.3
	tempdir-0.3.7
	tar-0.4.37
	directories-3.0.2
	vte_generate_state_changes-0.1.1
	digest-0.9.0
	block-buffer-0.9.0
	crypto-mac-0.10.1
	crypto-mac-0.8.0
	flate2-1.0.22
	rand_chacha-0.2.2
	rand_chacha-0.3.1
	url-2.2.2
	skeptic-0.4.0
	http-0.1.21
	md-5-0.9.1
	sha-1-0.9.8
	sha2-0.9.8
	hmac-0.10.1
	env_logger-0.8.4
	rand-0.7.3
	openssl-sys-0.9.70
	zstd-sys-1.4.20+zstd.1.4.9
	blake3-0.3.8
	ring-0.16.20
	rand-0.8.4
	vte-0.10.1
	local-encoding-0.2.0
	memcached-rs-0.4.2
	retry-1.3.0
	hyperx-0.13.2
	tempfile-3.2.0
	strip-ansi-escapes-0.1.1
	tokio-macros-1.5.1
	tracing-attributes-0.1.18
	pin-project-internal-1.0.8
	thiserror-impl-1.0.30
	tracing-0.1.29
	pin-project-1.0.8
	tower-0.4.10
	tokio-serde-0.8.0
	tokio-util-0.6.9
	tokio-native-tls-0.3.0
	thiserror-1.0.30
	futures-executor-0.3.17
	h2-0.3.7
	combine-4.6.2
	zip-0.5.13
	futures-0.3.17
	futures-locks-0.6.0
	serde_urlencoded-0.7.0
	toml-0.5.8
	bincode-1.3.3
	chrono-0.4.19
	hyper-0.14.14
	redis-0.21.4
	zstd-0.6.1+zstd.1.4.9
	hyper-tls-0.5.0
	reqwest-0.11.6
"

inherit cargo optfeature

DESCRIPTION="Sccache is a ccache-like tool. It is used as a compiler wrapper and avoids compilation when possible, storing a cache in a remote storage using the S3 API."

# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/mozilla/sccache/"

if [ -z "${MY_COMMIT}" ]; then
	SRC_URI="https://github.com/mozilla/${PN}/archive/${PV}.tar.gz -> ${P}.tar.gz"
else
	SRC_URI="https://github.com/mozilla/${PN}/archive/${MY_COMMIT}.tar.gz -> ${P}.tar.gz"
	S="${WORKDIR}/${PN}-${MY_COMMIT}"
fi

SRC_URI="${SRC_URI} $(cargo_crate_uris ${CRATES})"

S="${WORKDIR}/${PN}-${MY_COMMIT}"
RESTRICT="mirror"

# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="0BSD Apache-2.0 Apache-2.0-WITH-LLVM-exception BSD-2-Clause BSD-3-Clause BSL-1.0 CC0-1.0 ISC MIT MPL-2.0 Unlicense Zlib"
SLOT="0"
KEYWORDS="~amd64"
IUSE="azure dist-client dist-server gcs memcached redis s3"

DEPEND="
	dist-server? ( dev-libs/openssl:0= )
	gcs? ( dev-libs/openssl:0= )
"

RDEPEND="${DEPEND}
	dist-server? ( sys-apps/bubblewrap )
"

QA_FLAGS_IGNORED="usr/bin/sccache*"

src_configure() {
	myfeatures=(
		$(usev azure)
		$(usev dist-client)
		$(usev dist-server)
		$(usev gcs)
		$(usev memcached)
		$(usev redis)
		$(usev s3)
	)
	cargo_src_configure --no-default-features
}

src_install() {
	cargo_src_install

	keepdir /etc/sccache

	einstalldocs
	dodoc -r docs/.

	if use dist-server; then
		newinitd "${FILESDIR}"/server.initd sccache-server
		newconfd "${FILESDIR}"/server.confd sccache-server

		newinitd "${FILESDIR}"/scheduler.initd sccache-scheduler
		newconfd "${FILESDIR}"/scheduler.confd sccache-scheduler
	fi
}

pkg_postinst() {
	ewarn "${PN} is experimental, please use with care"
	use memcached && optfeature "memcached backend support" net-misc/memcached
	use redis && optfeature "redis backend support" dev-db/redis
}
